
CREATE PROCEDURE [dbo].[GetPastRangeDraws](@db int, @targetDraw int, @range int) AS

	IF (@db = 0)
		SELECT * FROM Lottery WHERE Lottery.DrawNumber <= @targetDraw AND 
			Lottery.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 1
		SELECT * FROM LottoMax WHERE LottoMax.DrawNumber <= @targetDraw AND 
			LottoMax.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 2
		SELECT * FROM BC49 WHERE BC49.DrawNumber <= @targetDraw AND 
			BC49.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 3
		SELECT * FROM FloridaLotto WHERE FloridaLotto.DrawNumber <= @targetDraw AND 
			FloridaLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 4
		SELECT * FROM MegaMillions WHERE MegaMillions.DrawNumber <= @targetDraw AND 
			MegaMillions.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 5
		SELECT * FROM MegaMillions_MegaBall WHERE MegaMillions_MegaBall.DrawNumber <= @targetDraw AND 
			MegaMillions_MegaBall.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 6
		SELECT * FROM PowerBall WHERE PowerBall.DrawNumber <= @targetDraw AND 
			PowerBall.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 7
		SELECT * FROM PowerBall_PowerBall WHERE PowerBall_PowerBall.DrawNumber <= @targetDraw AND 
			PowerBall_PowerBall.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 8
		SELECT * FROM NYLotto WHERE NYLotto.DrawNumber <= @targetDraw AND 
			NYLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 9
		SELECT * FROM EuroMillions WHERE EuroMillions.DrawNumber <= @targetDraw AND 
			EuroMillions.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 10
		SELECT * FROM EuroMillions_LuckyStars WHERE EuroMillions_LuckyStars.DrawNumber <= @targetDraw AND 
			EuroMillions_LuckyStars.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 11
		SELECT * FROM OZLotto WHERE OZLotto.DrawNumber <= @targetDraw AND 
			OZLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 12
		SELECT * FROM SSQ WHERE SSQ.DrawNumber <= @targetDraw AND 
			SSQ.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 13
		SELECT * FROM SSQ_Blue WHERE SSQ_Blue.DrawNumber <= @targetDraw AND 
			SSQ_Blue.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 14
		SELECT * FROM SevenLotto WHERE SevenLotto.DrawNumber <= @targetDraw AND 
			SevenLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 15
		SELECT * FROM SuperLotto WHERE SuperLotto.DrawNumber <= @targetDraw AND 
			SuperLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 16
		SELECT * FROM SuperLotto_Rear WHERE SuperLotto_Rear.DrawNumber <= @targetDraw AND 
			SuperLotto_Rear.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 17
		SELECT * FROM NYSweetMillion WHERE NYSweetMillion.DrawNumber <= @targetDraw AND 
			NYSweetMillion.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 18
		SELECT * FROM ColoradoLotto WHERE ColoradoLotto.DrawNumber <= @targetDraw AND 
			ColoradoLotto.DrawNumber >= @targetDraw - @range
	ELSE IF @db = 19
		SELECT * FROM FloridaMega WHERE FloridaMega.DrawNumber <= @targetDraw AND 
			FloridaMega.DrawNumber >= @targetDraw - @range
